# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: matthewbusche.com

# A description of your site for social meta tag, search engines, and feed.xml
description: "Developer at Nationwide Insurance"

# Tagline near the site title
tagline: "Things I've learned"

# The subpath of your site, e.g. /blog, for generating urls
# baseurl

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://matthewbusche.com"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects/
  - text: Presentations
    url: /presentations/
  - text: Contact
    url: /contact/
  - text: Search
    url: /search/

  # The shortname for your Disqus site to enable comments.
# disqus

# Author information - author info at the bottom of the post
author_name: "Matt Busche"
author_bio: "Matt is a developer at Nationwide Insurance."
author_url: "https://www.matthewbusche.com"
author_location: "Des Moines, IA"
#author_image: /images/avatar.jpg

# Sidebar Add banner
# banner_url
# banner_image

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url

# Social links in the site footer
twitter_username: mrbusche
#facebook_username: "username"
#googleplus_username: "+username"
github_username: mrbusche
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
linkedin_username: mrbusche
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"
plugins: ["jekyll-paginate", "jekyll-redirect-from"]
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false

include:
  - _redirects
