name: Check spelling
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@0.4.0
